# Generated by Django 4.0.4 on 2022-07-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reciperequirement_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='require',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
    ]
