# Generated by Django 4.0.4 on 2022-07-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_purchase_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='time_create',
            field=models.DateTimeField(default='0'),
        ),
    ]
