# Generated by Django 4.0.4 on 2022-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_purchase_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
