# Generated by Django 4.0.4 on 2022-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchase_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g.', 'grams'), ('kg.', 'kilos'), ('L.', 'liters'), ('ml.', 'milliliters'), ('num', 'amount')], default='num', max_length=3),
        ),
    ]
