# Generated by Django 4.0.4 on 2022-07-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g.', 'grams'), ('kg.', 'kilos'), ('L.', 'liters'), ('ml.', 'milliliters'), ('num', 'amount')], default='num', max_length=3),
        ),
    ]
